### ISSUE TITLE
erroneous comma in .rs output

### ISSUE THREAD

**Issue by HeathenHacker** [cenotelie/hime#80]
using himecc 4.2.0 to generate a parser from a grammar with syntactic actions generates the function 
```rust
/// Parses the specified string with this parser
pub fn parse_string(input: String) -> ParseResult<'static, 'static, 'static> {
    let text = Text::from_string(input);
    parse_text(text, , &mut NoActions {})
}
```
with one too many commas in the parse_text call

**Comment by woutersl** [comment]
Good catch, thank you for the feedback.
This has been fixed in 4.2.1 and subsequent versions.
